export const SELF_HARM_KEYWORDS = [
  // English
  "suicide",
  "suicidal",
  "kill myself",
  "kms",
  "end my life",
  "take my life",
  "self harm",
  "self-harm",
  "cut myself",
  "hurt myself",
  "harm myself",
  "i want to die",
  "i don't want to live",
  "overdose myself",

  // Spanish / es-419
  "suicidio",
  "suicidarme",
  "suicida",
  "matarme",
  "me quiero morir",
  "quiero morirme",
  "quiero matarme",
  "quitarme la vida",
  "terminar con mi vida",
  "hacerme daño",
  "autolesion",
  "autolesión",
  "autolesionarme",
  "cortarme",
  "me voy a matar",
  "no quiero vivir",

  // Portuguese / pt-BR
  "suicídio",
  "suicidio",
  "suicida",
  "me matar",
  "quero morrer",
  "queria morrer",
  "quero me matar",
  "vou me matar",
  "tirar minha vida",
  "acabar com minha vida",
  "me machucar",
  "me ferir",
  "automutilação",
  "automutilacao",
  "me cortar",
  "não quero viver",
  "nao quero viver",
];

export const VIOLENCE_KEYWORDS = [
  // English
  "kill",
  "murder",
  "hurt",
  "harm",
  "attack",
  "assault",
  "beat up",
  "punch",
  "stab",
  "shoot",
  "strangle",
  "choke",
  "torture",
  "maim",
  "mutilate",
  "kidnap",
  "poison",
  "bomb",
  "arson",
  "burn down",
  "destroy property",
  "vandalize",
  "weapon",
  "gun",
  "knife",

  // Spanish / es-419
  "matar",
  "asesinar",
  "hacer daño",
  "lastimar",
  "golpear",
  "pegarle",
  "atacar",
  "agredir",
  "apuñalar",
  "disparar",
  "ahorcar",
  "estrangular",
  "torturar",
  "mutilar",
  "secuestrar",
  "envenenar",
  "bomba",
  "quemar",
  "incendiar",
  "destruir propiedad",
  "vandalizar",
  "arma",
  "pistola",
  "cuchillo",
  "navaja",

  // Portuguese / pt-BR
  "matar",
  "assassinar",
  "machucar",
  "ferir",
  "agredir",
  "bater",
  "espancar",
  "atacar",
  "esfaquear",
  "atirar",
  "enforcar",
  "estrangular",
  "torturar",
  "mutilar",
  "sequestrar",
  "envenenar",
  "bomba",
  "queimar",
  "incendiar",
  "destruir propriedade",
  "vandalizar",
  "arma",
  "revólver",
  "revolver",
  "pistola",
  "faca",
  "canivete",
];

export const NSFW_KEYWORDS = [
  // English
  "porn",
  "pornography",
  "sex",
  "sexual",
  "explicit",
  "nude",
  "naked",
  "fetish",
  "kink",
  "bdsm",
  "incest",
  "rape",
  "molest",
  "minor",
  "underage",
  "child porn",
  "pedo",
  "pedophile",

  // Spanish / es-419
  "porno",
  "pornografía",
  "pornografia",
  "sexo",
  "sexual",
  "explícito",
  "explicito",
  "desnudo",
  "desnuda",
  "fetiche",
  "morbo",
  "incesto",
  "violar",
  "violación",
  "violacion",
  "abusar",
  "abuso sexual",
  "menor de edad",
  "menores",
  "niño",
  "niña",
  "niños",
  "niñas",
  "adolescente",
  "pedófilo",
  "pedofilo",
  "pederasta",

  // Portuguese / pt-BR
  "pornô",
  "porno",
  "pornografia",
  "sexo",
  "sexual",
  "explícito",
  "explicito",
  "nu",
  "nua",
  "nudez",
  "pelado",
  "pelada",
  "fetiche",
  "tarado",
  "tarada",
  "incesto",
  "estuprar",
  "estupro",
  "abusar",
  "abuso sexual",
  "menor de idade",
  "menores",
  "criança",
  "crianca",
  "crianças",
  "criancas",
  "adolescente",
  "pedófilo",
  "pedofilo",
  "pedofilia",
];

export const HATE_HARASSMENT_KEYWORDS = [
  // English general abuse
  "slur",
  "racist",
  "racism",
  "hate speech",
  "nazi",
  "white power",

  // Spanish / es-419 general abuse
  "racista",
  "racismo",
  "discurso de odio",
  "nazi",
  "odio racial",

  // Portuguese / pt-BR general abuse
  "racista",
  "racismo",
  "discurso de ódio",
  "discurso de odio",
  "nazista",
  "ódio racial",
  "odio racial",
];

export const PROFANITY_AND_ABUSE_KEYWORDS = [
  // English
  "fuck",
  "shit",
  "bitch",
  "cunt",
  "asshole",
  "whore",
  "slut",
  "hoe",
  "dick",
  "pussy",
  "retard",
  "faggot",

  // Spanish / es-419 broad profanity / abuse
  "puta",
  "puto",
  "putita",
  "perra",
  "zorra",
  "pendejo",
  "pendeja",
  "pendejito",
  "pendejita",
  "cabron",
  "cabrón",
  "cabrona",
  "chingar",
  "chingada",
  "chingado",
  "chingadera",
  "mierda",
  "carajo",
  "coño",
  "cono",
  "verga",
  "marica",
  "maricón",
  "maricon",
  "joto",
  "culero",
  "culera",
  "pelotudo",
  "pelotuda",
  "boludo",
  "boluda",
  "gilipollas",
  "imbecil",
  "imbécil",
  "idiota",
  "estupido",
  "estúpido",
  "estupida",
  "estúpida",

  // Portuguese / pt-BR broad profanity / abuse
  "porra",
  "caralho",
  "merda",
  "puta",
  "puto",
  "vadia",
  "vagabunda",
  "vagabundo",
  "piranha",
  "buceta",
  "boceta",
  "pau",
  "pinto",
  "cacete",
  "cu",
  "cuzao",
  "cuzão",
  "arrombado",
  "arrombada",
  "foder",
  "fodido",
  "fodida",
  "viado",
  "bicha",
  "traveco",
  "retardado",
  "retardada",
  "idiota",
  "imbecil",
  "imbécil",
  "otario",
  "otário",
];

export const CHILD_TERMS = [
  // English
  "child",
  "children",
  "kid",
  "kids",
  "toddler",
  "preschool",
  "youth",
  "teen",
  "teenager",
  "minor",
  "underage",

  // Spanish / es-419
  "niño",
  "niña",
  "niños",
  "niñas",
  "menor",
  "menores",
  "menor de edad",
  "adolescente",
  "adolescentes",

  // Portuguese / pt-BR
  "criança",
  "crianca",
  "crianças",
  "criancas",
  "menor",
  "menores",
  "menor de idade",
  "adolescente",
  "adolescentes",
];

export const ANIMAL_HARM_KEYWORDS = [
  // English
  "kill animal",
  "hurt animal",
  "harm animal",
  "abuse animal",
  "torture animal",
  "kill dog",
  "kill cat",
  "hurt dog",
  "hurt cat",
  "kill pet",
  "hurt pet",

  // Spanish / es-419
  "matar animal",
  "lastimar animal",
  "hacer daño a un animal",
  "maltratar animal",
  "torturar animal",
  "matar perro",
  "matar gato",
  "lastimar perro",
  "lastimar gato",
  "maltratar mascota",

  // Portuguese / pt-BR
  "matar animal",
  "machucar animal",
  "ferir animal",
  "maltratar animal",
  "torturar animal",
  "matar cachorro",
  "matar gato",
  "machucar cachorro",
  "machucar gato",
  "maltratar pet",
];

export const DANGEROUS_CONTENT_KEYWORDS = [
  ...VIOLENCE_KEYWORDS,
  ...NSFW_KEYWORDS,
  ...HATE_HARASSMENT_KEYWORDS,
  ...ANIMAL_HARM_KEYWORDS,

  // Drugs / overdose / poisoning
  "drug",
  "drugs",
  "overdose",
  "poison",
  "cocaine",
  "heroin",
  "meth",
  "droga",
  "drogas",
  "sobredosis",
  "envenenar",
  "veneno",
  "cocaína",
  "cocaina",
  "heroína",
  "heroina",
  "metanfetamina",
];

export const ALL_BLOCKLIST_KEYWORDS = [
  ...SELF_HARM_KEYWORDS,
  ...DANGEROUS_CONTENT_KEYWORDS,
  ...PROFANITY_AND_ABUSE_KEYWORDS,
];

export function normalizedIncludesAny(input: string, keywords: string[]): boolean {
  const normalized = input
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "");

  return keywords.some((keyword) => {
    const normalizedKeyword = keyword
      .toLowerCase()
      .normalize("NFD")
      .replace(/\p{Diacritic}/gu, "");

    return normalized.includes(normalizedKeyword);
  });
}
