export function BillingRefundPolicyContentFR() {
  return (
    <>
      <h1 className="text-4xl font-bold mb-6">Politique de facturation et de remboursement</h1>
      <p className="text-sm text-muted-foreground mb-8">
        <strong>Date d’entrée en vigueur :</strong> 13 janvier 2025<br />
        <strong>Société :</strong> Palette Plotting LLC (&quot;Palette Plotting&quot;, &quot;nous&quot;, &quot;notre&quot;, &quot;nos&quot;)
      </p>
      <div className="space-y-6 prose prose-sm max-w-none">
        <p className="text-muted-foreground mb-4"># Politique de facturation et de remboursement</p>
        <p className="text-muted-foreground mb-4">Cette Politique de facturation et de remboursement (&quot;Politique&quot;) explique le fonctionnement des abonnements, paiements, renouvellements, annulations et remboursements pour Palette Plotting. Votre mode de paiement dépend de l’endroit où vous vous abonnez : sur le site web, les abonnements sont traités par Stripe ; dans l’application iOS, les abonnements sont achetés via l’Apple App Store et Apple traite le paiement ; dans l’application Android, les abonnements sont achetés via Google Play et Google traite le paiement. Les demandes de remboursement pour iOS doivent être soumises à Apple, et celles pour Google Play via Google Play ou votre historique de commandes. Palette Plotting ne traite pas ces remboursements. Cette Politique fonctionne avec nos Conditions d’utilisation et notre Politique de confidentialité. En vous abonnant, vous acceptez cette Politique.</p>
        <h2 className="text-2xl font-semibold mb-4">1. Formules d’abonnement</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting propose des formules payantes, notamment mensuelles et annuelles. Les noms, prix et fonctionnalités incluses peuvent changer à tout moment. Les prix sont affichés dans votre devise locale lorsqu’elle est disponible. Votre abonnement vous donne accès aux fonctionnalités premium pendant la période payée.</p>
        <h2 className="text-2xl font-semibold mb-4">2. Traitement des paiements</h2>
        <p className="text-muted-foreground mb-4">Les paiements sont traités par Stripe pour le web, Apple pour iOS et Google Play pour Android. Vos informations de paiement sont détenues par le processeur de paiement, non par Palette Plotting. Pour les abonnements web, vous autorisez Palette Plotting LLC et Stripe à stocker votre moyen de paiement, débiter automatiquement les frais d’abonnement applicables et percevoir les taxes requises. Pour les abonnements iOS, les conditions de paiement et de facturation d’Apple s’appliquent et vous pouvez gérer l’abonnement dans les paramètres de votre Apple ID.</p>
        <h2 className="text-2xl font-semibold mb-4">3. Renouvellement automatique</h2>
        <p className="text-muted-foreground mb-4">Les abonnements se renouvellent automatiquement à la fin de chaque période de facturation, sauf annulation préalable. Lors du renouvellement, votre moyen de paiement sera débité, la période sera prolongée pour la même durée et le prix en vigueur au moment du renouvellement s’appliquera. Nous vous informerons des changements de prix conformément à la loi applicable.</p>
        <h2 className="text-2xl font-semibold mb-4">4. Politique d’annulation</h2>
        <p className="text-muted-foreground mb-4">Vous pouvez annuler votre abonnement à tout moment. Web : via les paramètres du compte. iOS : via les réglages d’abonnement Apple ID ou l’App Store. Android : via Google Play Store ou votre compte Google. Après annulation, l’abonnement reste actif jusqu’à la fin de la période en cours, aucun remboursement n’est accordé pour la période en cours et l’accès aux fonctionnalités payantes prend fin à l’expiration de la période. Après annulation ou expiration, votre contenu utilisateur peut être supprimé définitivement, y compris analyses, journaux, ensembles d’affirmations, audios et autres données créées via le Service. Nous ne garantissons pas la conservation des données.</p>
        <h2 className="text-2xl font-semibold mb-4">5. Politique de remboursement</h2>
        <p className="text-muted-foreground mb-4">Votre satisfaction est importante. Nous ne garantissons pas les remboursements, mais examinons les demandes au cas par cas. Pour les abonnements web traités par Stripe, vous pouvez nous contacter pour demander un remboursement ; nous examinerons notamment les achats accidentels, problèmes techniques ou cas où le Service ne fonctionne pas comme décrit. Nous ne nous engageons pas à rembourser les périodes partielles, le temps non utilisé, les oublis d’annulation avant renouvellement ou la simple non-utilisation du Service, mais vous pouvez nous écrire. Les abonnements iOS sont remboursés uniquement par Apple. Les abonnements Android sont remboursés uniquement par Google Play. Si votre loi locale impose des droits de remboursement ou d’annulation pour les achats en ligne, nous nous y conformerons. Les utilisateurs de certaines régions, comme l’UE/Royaume-Uni, peuvent disposer de droits de rétractation limités pour les services numériques, uniquement lorsque la loi l’exige.</p>
        <h2 className="text-2xl font-semibold mb-4">6. Paiements échoués</h2>
        <p className="text-muted-foreground mb-4">Si un paiement échoue, Stripe peut réessayer automatiquement, l’accès premium peut être suspendu et votre abonnement peut être annulé si le paiement n’est pas effectué. Les problèmes Google Play sont gérés via Google Play Store ou votre compte Google. Vous êtes responsable de maintenir vos informations de paiement à jour.</p>
        <h2 className="text-2xl font-semibold mb-4">7. Offres promotionnelles</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting peut proposer des tarifs de lancement ou codes promotionnels. Les promotions s’appliquent uniquement pendant la période indiquée, peuvent se renouveler au tarif standard, ne peuvent pas être appliquées rétroactivement et peuvent être modifiées ou supprimées à tout moment.</p>
        <h2 className="text-2xl font-semibold mb-4">8. Taxes</h2>
        <p className="text-muted-foreground mb-4">Les achats peuvent être soumis à des taxes, telles que taxe de vente, TVA ou GST, selon votre localisation. Stripe calcule et collecte les taxes lorsque nécessaire. Pour Google Play, Google peut calculer, collecter et reverser les taxes applicables selon ses politiques et votre région.</p>
        <h2 className="text-2xl font-semibold mb-4">9. Rétrofacturations et litiges</h2>
        <p className="text-muted-foreground mb-4">Si vous contestez un débit auprès de votre banque au lieu de nous contacter d’abord, votre compte peut être suspendu pendant la résolution, vous restez responsable des frais légitimes, et nous pouvons fournir à Stripe et à votre banque des documents à l’appui de la transaction. Nous vous encourageons à nous contacter directement avant d’ouvrir un litige.</p>
        <h2 className="text-2xl font-semibold mb-4">10. Modifications des conditions de facturation</h2>
        <p className="text-muted-foreground mb-4">Nous pouvons modifier cette Politique occasionnellement. Votre utilisation continue du Service après les changements vaut acceptation de la Politique mise à jour. Nous respecterons les exigences de notification concernant les changements de prix lorsque celles-ci s’appliquent.</p>
        <h2 className="text-2xl font-semibold mb-4">11. Contact</h2>
        <p className="text-muted-foreground mb-4">Pour toute question ou assistance liée à la facturation : support@paletteplot.com</p>
      </div>
    </>
  );
}
