export function TermsOfServiceContentES() {
  return (
    <>
      <h1 className="text-4xl font-bold mb-6">Términos de Uso y EULA</h1>
      <p className="text-sm text-muted-foreground mb-8">
        <strong>Fecha de entrada en vigor:</strong> 13 de enero de 2025<br />
        <strong>Compañía:</strong> Palette Plotting LLC (“Palette Plotting”, “nosotros”, “nuestro”, “nos”)
      </p>
      <p className="text-sm text-muted-foreground mb-8">
        <strong>Última actualización:</strong> 13 de enero de 2025
      </p>
      <div className="space-y-6 prose prose-sm max-w-none">
        <p className="text-muted-foreground mb-4"># Términos de Uso y EULA</p>
        <h2 className="text-2xl font-semibold mb-4">Términos de Uso</h2>
        <p className="text-muted-foreground mb-4">Estos Términos de Uso (“Términos”) rigen tu acceso y uso de Palette Plotting, incluyendo todas las herramientas digitales, funciones, contenido y servicios ofrecidos a través de nuestro sitio web, app o PWA (colectivamente, el “Servicio”). Al usar el Servicio, aceptas estos Términos. Si no aceptas, no uses el Servicio.</p>
        <h2 className="text-2xl font-semibold mb-4">1. Elegibilidad</h2>
        <p className="text-muted-foreground mb-4">El Servicio está destinado a personas de 18 años o más. No puedes usar el Servicio si tienes menos de 18 años.</p>
        <h2 className="text-2xl font-semibold mb-4">2. Descripción del Servicio</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting proporciona herramientas digitales destinadas a apoyar la reflexión personal, la fijación de metas, el journaling, la creación de audio y el desarrollo de mentalidad. Algunas partes del Servicio pueden incluir funciones automatizadas, sugerencias generadas por el sistema o contenido asistido por tecnología. El Servicio no es asesoramiento médico, psicológico, terapéutico, financiero ni legal, y no sustituye el apoyo profesional. Podemos actualizar o modificar funciones del Servicio en cualquier momento.</p>
        <h2 className="text-2xl font-semibold mb-4">3. Registro de cuenta</h2>
        <p className="text-muted-foreground mb-4">Para usar ciertas funciones, es posible que debas crear una cuenta. Aceptas proporcionar información precisa, mantener la confidencialidad de tus credenciales de inicio de sesión y notificarnos cualquier uso no autorizado. Eres responsable de la actividad que ocurra en tu cuenta.</p>
        <h2 className="text-2xl font-semibold mb-4">4. Uso aceptable</h2>
        <p className="text-muted-foreground mb-4">Debes cumplir nuestra Política de Uso Aceptable, incorporada por referencia y disponible por separado. Las conductas prohibidas incluyen, entre otras: acoso, abuso o conducta de odio; subir o compartir contenido ilícito o inapropiado; fraude, suplantación o tergiversación; intentar interferir con el Servicio o interrumpirlo; usar el Servicio para fines ilegales o inseguros; intentar evadir protecciones del sistema; explotar menores o publicar contenido que involucre menores en contextos inapropiados; y subir contenido protegido por derechos de autor sin permiso. Podemos suspender o cancelar tu cuenta por infracciones.</p>
        <h2 className="text-2xl font-semibold mb-4">5. Contenido del usuario</h2>
        <p className="text-muted-foreground mb-4">“Contenido del usuario” incluye texto, audio, notas, entradas de diario, afirmaciones, composiciones musicales u otro material que ingreses o generes a través del Servicio. Permites que Palette Plotting y los proveedores de infraestructura que apoyan el Servicio alojen, almacenen, transmitan y procesen técnicamente tu Contenido del usuario solo según sea necesario para guardarlo en tu cuenta, devolvértelo, sincronizarlo entre tus dispositivos y ejecutar las funciones que elijas usar, como generación de audio o formato. Este permiso es limitado, no exclusivo y libre de regalías, y se aplica solo mientras el contenido esté almacenado para tu cuenta. No usamos tu Contenido del usuario privado para publicidad, exhibición pública ni desarrollo general del producto, salvo que aceptes por separado, por ejemplo, entrenamiento opcional de datos en Ajustes. Palette Plotting no revisa rutinariamente diarios, afirmaciones o audios privados con fines editoriales o comerciales. Podemos eliminar contenido que viole estos Términos o la Política de Uso Aceptable.</p>
        <h2 className="text-2xl font-semibold mb-4">5a. Composición musical y derechos de autor</h2>
        <p className="text-muted-foreground mb-4">Al usar la función Music Composer, reconoces y aceptas que solo crearás composiciones musicales originales; no recrearás, copiarás ni imitarás melodías, canciones u obras musicales protegidas por derechos de autor; eres el único responsable de asegurarte de que tus composiciones no infrinjan derechos de autor, marcas comerciales ni derechos de propiedad intelectual existentes; e indemnizarás y mantendrás indemne a Palette Plotting frente a cualquier reclamación derivada de infracción de derechos de autor en tus composiciones. Violar estos términos puede resultar en la eliminación inmediata del contenido y la cancelación de la cuenta.</p>
        <h2 className="text-2xl font-semibold mb-4">6. Contenido asistido por tecnología y generado por el sistema</h2>
        <p className="text-muted-foreground mb-4">Algunas funciones pueden ofrecer respuestas automatizadas, sugerencias o contenido generado por IA para apoyar tu reflexión u objetivos creativos. Reconoces que dicho contenido puede ser imperfecto o incompleto, no sustituye el asesoramiento profesional y tú eres responsable de cómo lo usas. Podemos ajustar o limitar estas funciones en cualquier momento.</p>
        <h2 className="text-2xl font-semibold mb-4">7. Notificaciones de metas</h2>
        <p className="text-muted-foreground mb-4">Las notificaciones de metas pueden configurarse usando herramientas o servicios externos elegidos por el usuario, como integraciones de calendario, automatizaciones del dispositivo o accesos directos del sistema operativo. Estas herramientas pueden recordar a los usuarios revisar metas, abrir check-ins semanales o acceder a áreas específicas del Servicio en horarios seleccionados. Palette Plotting actualmente no envía notificaciones de metas por SMS/correo electrónico y no controla, opera ni garantiza el rendimiento de calendarios de terceros, automatizaciones del dispositivo o funciones del sistema operativo. Palette Plotting no es responsable de alertas perdidas, fallas de entrega, errores de programación, ajustes del dispositivo o cambios realizados por proveedores externos. El uso de herramientas externas de notificación es opcional y gestionado completamente por el usuario.</p>
        <h2 className="text-2xl font-semibold mb-4">8. Suscripciones y facturación</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting ofrece planes de suscripción, incluyendo opciones mensuales o anuales. Los nombres y precios de los planes pueden cambiar. Las funciones incluidas en cada nivel, los niveles de acceso a funcionalidades específicas, los límites como mensajes diarios, creaciones semanales y cuotas de almacenamiento, y otros beneficios pueden cambiar en cualquier momento sin aviso previo. Nos reservamos el derecho de modificar, agregar o eliminar funciones, ajustar límites, cambiar niveles de acceso o alterar cualquier aspecto de los niveles de suscripción según sea necesario para mantener la calidad del servicio, prevenir abusos o adaptarnos a requisitos operativos. El uso continuo del Servicio después de esos cambios constituye aceptación. Todas las ventas son finales, salvo cuando lo exija la ley aplicable. Las suscripciones in-app compradas por Android usan el sistema de facturación de Google Play. Pagos, renovaciones, cancelaciones y solicitudes de reembolso se manejan bajo las políticas de Google; presenta solicitudes de reembolso por Google Play, no por Palette Plotting. Al suscribirte, autorizas la facturación recurrente hasta cancelar. Las cancelaciones surten efecto al final del período de facturación actual. No ofrecemos reembolsos por períodos parciales o tiempo no usado. En caso de vencimiento o cancelación, tu contenido de usuario, incluyendo análisis de estructuras de creencias, entradas de diario, conjuntos de afirmaciones, audios creados en el Servicio y otros datos creados a través del Servicio, puede eliminarse permanentemente. No garantizamos la retención de datos.</p>
        <h2 className="text-2xl font-semibold mb-4">9. Propiedad intelectual</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting y todo el contenido, marca, diseño y materiales asociados pertenecen a Palette Plotting LLC o sus licenciantes. No puedes copiar o distribuir el Servicio, hacer ingeniería inversa del software, usar indebidamente marcas o branding, ni crear obras derivadas de la plataforma.</p>
        <h2 className="text-2xl font-semibold mb-4">10. Cambios en el Servicio</h2>
        <p className="text-muted-foreground mb-4">Podemos modificar, discontinuar o actualizar cualquier parte del Servicio en cualquier momento. No somos responsables por cambios, suspensiones o interrupciones del servicio.</p>
        <h2 className="text-2xl font-semibold mb-4">11. Descargos</h2>
        <p className="text-muted-foreground mb-4">El Servicio se proporciona “tal cual” y “según disponibilidad”. No garantizamos resultados específicos, disponibilidad ininterrumpida ni precisión del contenido generado por el sistema. Rechazamos todas las garantías en la máxima medida permitida por la ley.</p>
        <h2 className="text-2xl font-semibold mb-4">12. Limitación de responsabilidad</h2>
        <p className="text-muted-foreground mb-4">En la máxima medida permitida por la ley, Palette Plotting LLC no será responsable por daños indirectos, incidentales, especiales, consecuentes o punitivos derivados de tu uso del Servicio. Nuestra responsabilidad total por cualquier reclamación no excederá el monto que pagaste en cuotas de suscripción durante los 12 meses anteriores a la reclamación.</p>
        <h2 className="text-2xl font-semibold mb-4">13. Indemnización</h2>
        <p className="text-muted-foreground mb-4">Aceptas indemnizar y mantener indemne a Palette Plotting LLC frente a reclamaciones derivadas de tu uso indebido del Servicio, tu violación de estos Términos o tu Contenido del usuario.</p>
        <h2 className="text-2xl font-semibold mb-4">14. Ley aplicable</h2>
        <p className="text-muted-foreground mb-4">Estos Términos se rigen por las leyes del Estado de Illinois, sin considerar reglas de conflicto de leyes.</p>
        <h2 className="text-2xl font-semibold mb-4">15. Cambios a los Términos</h2>
        <p className="text-muted-foreground mb-4">Podemos actualizar estos Términos. El uso continuo del Servicio indica aceptación de la versión actualizada.</p>
        <h2 className="text-2xl font-semibold mb-4">16. Contacto</h2>
        <p className="text-muted-foreground mb-4">Las preguntas pueden dirigirse a: support@paletteplot.com</p>
        <h2 className="text-2xl font-semibold mb-4">EULA</h2>
        <p className="text-muted-foreground mb-4">Este Contrato de Licencia de Usuario Final (“EULA”) es un acuerdo legal solo entre tú y Palette Plotting LLC, y no con Apple, Inc. (“Apple”). Palette Plotting es la única responsable de la Aplicación Licenciada y su contenido. Este EULA no puede establecer reglas de uso que entren en conflicto con los Apple Media Services Terms and Conditions a la Fecha de Entrada en Vigor, que reconoces haber tenido la oportunidad de revisar. Al acceder o usar Palette Plotting, aceptas quedar vinculado por este EULA.</p>
        <p className="text-muted-foreground mb-4">Sujeto a tu cumplimiento de este EULA, Palette Plotting te otorga una licencia limitada, no exclusiva, no transferible y revocable para usar la Aplicación Licenciada en productos de marca Apple que poseas o controles, según lo permitido por las Usage Rules de los Apple Media Services Terms and Conditions. Esta licencia permite que la Aplicación Licenciada sea accedida y usada por otras cuentas asociadas contigo mediante Family Sharing o compras por volumen.</p>
        <p className="text-muted-foreground mb-4">Palette Plotting es la única responsable de proporcionar mantenimiento y soporte respecto de la Aplicación Licenciada, según este EULA o la ley aplicable. Reconoces que Apple no tiene obligación alguna de proporcionar mantenimiento o soporte.</p>
        <p className="text-muted-foreground mb-4">Palette Plotting es la única responsable de cualquier garantía del producto, expresa o implícita por ley, en la medida en que no haya sido efectivamente excluida. Para compras hechas por App Store, incluyendo suscripciones in-app, si la Aplicación Licenciada no cumple con una garantía aplicable, puedes notificar a Apple y Apple reembolsará el precio de compra correspondiente a esa compra de App Store. Esto no aplica a compras o suscripciones hechas por nuestro sitio web u otros métodos de pago, como Stripe, que se rigen por nuestros Términos generales y política de facturación. En la máxima medida permitida por ley, Apple no tendrá otra obligación de garantía respecto de la Aplicación Licenciada, y cualquier otra reclamación, pérdida, responsabilidad, daño, costo o gasto atribuible a una falta de conformidad será responsabilidad exclusiva de Palette Plotting.</p>
        <p className="text-muted-foreground mb-4">Tú y Palette Plotting reconocen que Palette Plotting, no Apple, es responsable de atender cualquier reclamación tuya o de terceros relacionada con la Aplicación Licenciada o tu posesión y/o uso de ella, incluyendo reclamaciones de responsabilidad por producto, falta de conformidad con requisitos legales o regulatorios, y reclamaciones bajo leyes de protección al consumidor, privacidad o similares. Este EULA no puede limitar la responsabilidad de Palette Plotting más allá de lo permitido por ley.</p>
        <p className="text-muted-foreground mb-4">En caso de reclamación de un tercero de que la Aplicación Licenciada o tu posesión y uso de ella infringe derechos de propiedad intelectual, Palette Plotting, no Apple, será la única responsable de la investigación, defensa, arreglo y resolución de dicha reclamación.</p>
        <p className="text-muted-foreground mb-4">Declaras y garantizas que no te encuentras en un país sujeto a embargo del Gobierno de EE. UU. o designado como país que “apoya el terrorismo”, y que no figuras en listas del Gobierno de EE. UU. de partes prohibidas o restringidas.</p>
        <p className="text-muted-foreground mb-4">La Aplicación Licenciada es licenciada por Palette Plotting LLC. Preguntas, quejas o reclamaciones relacionadas con la Aplicación Licenciada deben enviarse a support@paletteplot.com. Para dirección postal, contáctanos al correo anterior.</p>
        <p className="text-muted-foreground mb-4">Debes cumplir los términos aplicables de terceros al usar la Aplicación Licenciada, por ejemplo, no violar tu contrato de servicio de datos inalámbricos.</p>
        <p className="text-muted-foreground mb-4">Tú y Palette Plotting reconocen y aceptan que Apple y sus subsidiarias son terceros beneficiarios de este EULA y que, al aceptar sus términos, Apple tendrá derecho a hacer cumplir este EULA contra ti como tercero beneficiario.</p>
        <p className="text-muted-foreground mb-4">No puedes copiar, modificar o crear obras derivadas del Servicio; hacer ingeniería inversa, descompilar o desensamblar el Servicio; eliminar avisos o etiquetas de propiedad; alquilar, arrendar, prestar o vender acceso al Servicio; usar el Servicio para fines ilegales; o interferir con el Servicio o los servidores.</p>
        <p className="text-muted-foreground mb-4">El Servicio, incluyendo todo contenido, funciones y funcionalidad, pertenece a Palette Plotting y está protegido por leyes de derechos de autor, marcas y propiedad intelectual. Este EULA no te otorga derechos para usar nuestras marcas, logotipos u otros elementos de marca.</p>
        <p className="text-muted-foreground mb-4">Permites que Palette Plotting aloje, almacene, transmita y procese técnicamente tu contenido solo según sea necesario para proporcionar la Aplicación Licenciada a tu cuenta, como se describe en la sección Contenido del usuario.</p>
        <p className="text-muted-foreground mb-4">Esta licencia sigue vigente hasta su terminación. Podemos terminar o suspender tu acceso inmediatamente, sin aviso previo, por cualquier incumplimiento de este EULA. Al terminar, tu derecho a usar el Servicio cesará inmediatamente.</p>
        <p className="text-muted-foreground mb-4">EL SERVICIO SE PROPORCIONA “TAL CUAL” Y “SEGÚN DISPONIBILIDAD”, SIN GARANTÍAS DE NINGÚN TIPO, EXPRESAS O IMPLÍCITAS, INCLUYENDO GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN PROPÓSITO PARTICULAR O NO INFRACCIÓN.</p>
        <p className="text-muted-foreground mb-4">EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, PALETTE PLOTTING NO SERÁ RESPONSABLE POR DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENTES O PUNITIVOS, NI POR PÉRDIDA DE GANANCIAS O INGRESOS, YA SEA DIRECTA O INDIRECTA.</p>
        <p className="text-muted-foreground mb-4">Nos reservamos el derecho de modificar, actualizar o discontinuar el Servicio en cualquier momento. También podemos actualizar este EULA periódicamente. Tu uso continuo del Servicio después de esos cambios constituye aceptación del EULA actualizado.</p>
        <p className="text-muted-foreground mb-4">Este EULA se regirá e interpretará conforme a las leyes aplicables, sin considerar disposiciones de conflicto de leyes. Para preguntas sobre este EULA, contáctanos en support@paletteplot.com</p>
      </div>
    </>
  );
}
