export function TermsOfServiceContentPT() {
  return (
    <>
      <h1 className="text-4xl font-bold mb-6">Termos de Uso e EULA</h1>
      <p className="text-sm text-muted-foreground mb-8">
        <strong>Data de vigência:</strong> 13 de janeiro de 2025<br />
        <strong>Empresa:</strong> Palette Plotting LLC (“Palette Plotting”, “nós”, “nosso”, “nos”)
      </p>
      <p className="text-sm text-muted-foreground mb-8">
        <strong>Última atualização:</strong> 13 de janeiro de 2025
      </p>
      <div className="space-y-6 prose prose-sm max-w-none">
        <p className="text-muted-foreground mb-4"># Termos de Uso e EULA</p>
        <h2 className="text-2xl font-semibold mb-4">Termos de Uso</h2>
        <p className="text-muted-foreground mb-4">Estes Termos de Uso (“Termos”) regem seu acesso e uso da Palette Plotting, incluindo todas as ferramentas digitais, recursos, conteúdos e serviços oferecidos por meio do nosso site, app ou PWA (coletivamente, o “Serviço”). Ao usar o Serviço, você concorda com estes Termos. Se você não concordar, não use o Serviço.</p>
        <h2 className="text-2xl font-semibold mb-4">1. Elegibilidade</h2>
        <p className="text-muted-foreground mb-4">O Serviço é destinado a pessoas com 18 anos ou mais. Você não pode usar o Serviço se tiver menos de 18 anos.</p>
        <h2 className="text-2xl font-semibold mb-4">2. Visão geral do Serviço</h2>
        <p className="text-muted-foreground mb-4">A Palette Plotting fornece ferramentas digitais destinadas a apoiar reflexão pessoal, definição de metas, diário, criação de áudio e desenvolvimento de mentalidade. Certas partes do Serviço podem incluir recursos automatizados, sugestões geradas pelo sistema ou conteúdo assistido por tecnologia. O Serviço não é aconselhamento médico, psicológico, terapêutico, financeiro ou jurídico, e não substitui suporte profissional. Podemos atualizar ou modificar recursos do Serviço a qualquer momento.</p>
        <h2 className="text-2xl font-semibold mb-4">3. Registro de conta</h2>
        <p className="text-muted-foreground mb-4">Para usar certos recursos, talvez você precise criar uma conta. Você concorda em fornecer informações precisas, manter a confidencialidade das suas credenciais de login e nos notificar sobre qualquer uso não autorizado. Você é responsável pela atividade que ocorrer na sua conta.</p>
        <h2 className="text-2xl font-semibold mb-4">4. Uso aceitável</h2>
        <p className="text-muted-foreground mb-4">Você deve cumprir nossa Política de Uso Aceitável, incorporada por referência e disponível separadamente. Condutas proibidas incluem, sem limitação: assédio, abuso ou conduta de ódio; envio ou compartilhamento de conteúdo ilícito ou inadequado; fraude, falsidade de identidade ou falsa declaração; tentativa de interferir ou interromper o Serviço; uso do Serviço para qualquer finalidade ilegal ou insegura; tentativa de burlar proteções do sistema; exploração de menores ou publicação de conteúdo envolvendo menores em contexto inadequado; e envio de conteúdo protegido por direitos autorais sem permissão. Podemos suspender ou encerrar sua conta por violações.</p>
        <h2 className="text-2xl font-semibold mb-4">5. Conteúdo do usuário</h2>
        <p className="text-muted-foreground mb-4">“Conteúdo do usuário” inclui texto, áudio, notas, entradas de diário, afirmações, composições musicais ou outro material que você insere ou gera por meio do Serviço. Você permite que a Palette Plotting e os provedores de infraestrutura que apoiam o Serviço hospedem, armazenem, transmitam e processem tecnicamente seu Conteúdo do usuário apenas conforme necessário para salvá-lo na sua conta, entregá-lo de volta a você, sincronizá-lo entre seus dispositivos e executar recursos que você escolha usar, como geração de áudio ou formatação. Essa permissão é limitada, não exclusiva e livre de royalties, e se aplica apenas enquanto o conteúdo estiver armazenado para sua conta. Não usamos seu Conteúdo do usuário privado para publicidade, exibição pública ou desenvolvimento geral do produto, a menos que você aceite separadamente, por exemplo, treinamento opcional de dados em Configurações. A Palette Plotting não revisa rotineiramente diários, afirmações ou áudios privados para fins editoriais ou comerciais. Podemos remover conteúdo que viole estes Termos ou a Política de Uso Aceitável.</p>
        <h2 className="text-2xl font-semibold mb-4">5a. Composição musical e direitos autorais</h2>
        <p className="text-muted-foreground mb-4">Ao usar o recurso Music Composer, você reconhece e concorda que criará apenas composições musicais originais; não recriará, copiará ou imitará melodias, músicas ou obras musicais protegidas por direitos autorais; será o único responsável por garantir que suas composições não infrinjam direitos autorais, marcas registradas ou direitos de propriedade intelectual existentes; e indenizará e isentará a Palette Plotting de qualquer reivindicação decorrente de violação de direitos autorais em suas composições. A violação destes termos pode resultar na remoção imediata do conteúdo e no encerramento da conta.</p>
        <h2 className="text-2xl font-semibold mb-4">6. Conteúdo assistido por tecnologia e gerado pelo sistema</h2>
        <p className="text-muted-foreground mb-4">Alguns recursos podem oferecer respostas automatizadas, sugestões ou conteúdo gerado por IA para apoiar sua reflexão ou objetivos criativos. Você reconhece que esse conteúdo pode ser imperfeito ou incompleto, não substitui aconselhamento profissional e você é responsável por como o utiliza. Podemos ajustar ou limitar esses recursos a qualquer momento.</p>
        <h2 className="text-2xl font-semibold mb-4">7. Notificações de metas</h2>
        <p className="text-muted-foreground mb-4">Notificações de metas podem ser configuradas usando ferramentas ou serviços externos escolhidos pelo usuário, como integrações de calendário, automações de dispositivo ou atalhos no nível do sistema operacional. Essas ferramentas podem lembrar usuários de revisar metas, abrir check-ins semanais ou acessar áreas específicas do Serviço em horários selecionados. A Palette Plotting atualmente não envia notificações de metas por SMS/e-mail e não controla, opera ou garante o desempenho de calendários de terceiros, automações de dispositivo ou recursos do sistema operacional. A Palette Plotting não é responsável por alertas perdidos, falhas de entrega, erros de agendamento, configurações do dispositivo ou mudanças feitas por provedores terceiros. O uso de ferramentas externas de notificação é opcional e gerenciado inteiramente pelo usuário.</p>
        <h2 className="text-2xl font-semibold mb-4">8. Assinaturas e cobrança</h2>
        <p className="text-muted-foreground mb-4">A Palette Plotting oferece planos de assinatura, incluindo opções como planos mensais ou anuais. Nomes e preços de planos podem mudar. Recursos incluídos em cada nível de assinatura, níveis de acesso a funcionalidades específicas, limites de uso, como limites diários de mensagens, limites semanais de criação e cotas de armazenamento, e outros benefícios da assinatura estão sujeitos a alteração a qualquer momento sem aviso prévio. Reservamo-nos o direito de modificar, adicionar ou remover recursos, ajustar limites, alterar níveis de acesso ou alterar qualquer aspecto dos níveis de assinatura conforme necessário para manter a qualidade do serviço, prevenir abuso ou adaptar-nos a requisitos operacionais. O uso contínuo do Serviço após tais mudanças constitui aceitação das modificações. Todas as vendas são finais, exceto quando exigido pela lei aplicável. Assinaturas in-app compradas pelo app Android usam o sistema de cobrança do Google Play. Pagamentos, renovações, cancelamentos e pedidos de reembolso são tratados pelas políticas do Google; envie pedidos de reembolso pelo Google Play, não pela Palette Plotting. Ao assinar, você autoriza cobrança recorrente até cancelar. Cancelamentos entram em vigor ao fim do período de cobrança atual. Não oferecemos reembolsos por períodos parciais ou tempo não utilizado. Em caso de expiração ou cancelamento da assinatura, seu conteúdo do usuário, incluindo análises de estrutura de crenças, entradas de diário, conjuntos de afirmações, áudios criados no Serviço e outros dados criados por meio do Serviço, pode ser excluído permanentemente. Não garantimos retenção de dados.</p>
        <h2 className="text-2xl font-semibold mb-4">9. Propriedade intelectual</h2>
        <p className="text-muted-foreground mb-4">A Palette Plotting e todo conteúdo, marca, design e materiais associados pertencem à Palette Plotting LLC ou seus licenciadores. Você não pode copiar ou distribuir o Serviço, fazer engenharia reversa do software, usar indevidamente marcas ou identidade visual, nem criar obras derivadas da plataforma.</p>
        <h2 className="text-2xl font-semibold mb-4">10. Alterações no Serviço</h2>
        <p className="text-muted-foreground mb-4">Podemos modificar, descontinuar ou atualizar qualquer parte do Serviço a qualquer momento. Não somos responsáveis por alterações, suspensões ou interrupções do serviço.</p>
        <h2 className="text-2xl font-semibold mb-4">11. Isenções de responsabilidade</h2>
        <p className="text-muted-foreground mb-4">O Serviço é fornecido “no estado em que se encontra” e “conforme disponível”. Não garantimos resultados específicos, disponibilidade ininterrupta ou precisão de conteúdo gerado pelo sistema. Isentamo-nos de todas as garantias na máxima medida permitida por lei.</p>
        <h2 className="text-2xl font-semibold mb-4">12. Limitação de responsabilidade</h2>
        <p className="text-muted-foreground mb-4">Na máxima medida permitida por lei, a Palette Plotting LLC não será responsável por danos indiretos, incidentais, especiais, consequenciais ou punitivos decorrentes do seu uso do Serviço. Nossa responsabilidade total por qualquer reivindicação não excederá o valor que você pagou em taxas de assinatura nos 12 meses anteriores à reivindicação.</p>
        <h2 className="text-2xl font-semibold mb-4">13. Indenização</h2>
        <p className="text-muted-foreground mb-4">Você concorda em indenizar e isentar a Palette Plotting LLC de reivindicações decorrentes do seu uso indevido do Serviço, da sua violação destes Termos ou do seu Conteúdo do usuário.</p>
        <h2 className="text-2xl font-semibold mb-4">14. Lei aplicável</h2>
        <p className="text-muted-foreground mb-4">Estes Termos são regidos pelas leis do Estado de Illinois, sem considerar regras de conflito de leis.</p>
        <h2 className="text-2xl font-semibold mb-4">15. Alterações aos Termos</h2>
        <p className="text-muted-foreground mb-4">Podemos atualizar estes Termos. O uso contínuo do Serviço indica aceitação da versão atualizada.</p>
        <h2 className="text-2xl font-semibold mb-4">16. Contato</h2>
        <p className="text-muted-foreground mb-4">Dúvidas podem ser enviadas para: support@paletteplot.com</p>
        <h2 className="text-2xl font-semibold mb-4">EULA</h2>
        <p className="text-muted-foreground mb-4">Este Contrato de Licença de Usuário Final (“EULA”) é um acordo legal somente entre você e a Palette Plotting LLC, e não com a Apple, Inc. (“Apple”). A Palette Plotting é a única responsável pelo Aplicativo Licenciado e por seu conteúdo. Este EULA não pode estabelecer regras de uso que entrem em conflito com os Apple Media Services Terms and Conditions na Data de Vigência, que você reconhece ter tido a oportunidade de revisar. Ao acessar ou usar a Palette Plotting, você concorda em se vincular a este EULA.</p>
        <p className="text-muted-foreground mb-4">Sujeito ao seu cumprimento deste EULA, a Palette Plotting concede a você uma licença limitada, não exclusiva, intransferível e revogável para usar o Aplicativo Licenciado em produtos da marca Apple que você possua ou controle, conforme permitido pelas Usage Rules dos Apple Media Services Terms and Conditions. Essa licença permite que o Aplicativo Licenciado seja acessado e usado por outras contas associadas a você por Family Sharing ou compra por volume.</p>
        <p className="text-muted-foreground mb-4">A Palette Plotting é a única responsável por fornecer quaisquer serviços de manutenção e suporte relacionados ao Aplicativo Licenciado, conforme especificado neste EULA ou exigido pela lei aplicável. Você reconhece que a Apple não tem nenhuma obrigação de fornecer manutenção ou suporte para o Aplicativo Licenciado.</p>
        <p className="text-muted-foreground mb-4">A Palette Plotting é a única responsável por quaisquer garantias do produto, expressas ou implícitas por lei, na medida em que não tenham sido efetivamente renunciadas. Para compras feitas pela App Store, incluindo assinaturas in-app, se o Aplicativo Licenciado não estiver em conformidade com qualquer garantia aplicável, você poderá notificar a Apple, e a Apple reembolsará o preço de compra dessa compra na App Store. Isso não se aplica a compras ou assinaturas feitas pelo nosso site ou outros métodos de pagamento, como Stripe, que são regidos por nossos Termos de Uso gerais e política de cobrança. Na máxima medida permitida por lei, a Apple não terá nenhuma outra obrigação de garantia em relação ao Aplicativo Licenciado, e quaisquer outras reivindicações, perdas, responsabilidades, danos, custos ou despesas atribuíveis a falha de conformidade serão responsabilidade exclusiva da Palette Plotting.</p>
        <p className="text-muted-foreground mb-4">Você e a Palette Plotting reconhecem que a Palette Plotting, e não a Apple, é responsável por tratar quaisquer reivindicações suas ou de terceiros relacionadas ao Aplicativo Licenciado ou à sua posse e/ou uso dele, incluindo reivindicações de responsabilidade por produto, falha em cumprir requisitos legais ou regulatórios e reivindicações sob leis de proteção ao consumidor, privacidade ou similares. Este EULA não pode limitar a responsabilidade da Palette Plotting além do permitido por lei.</p>
        <p className="text-muted-foreground mb-4">Em caso de reivindicação de terceiro de que o Aplicativo Licenciado ou sua posse e uso dele infringe direitos de propriedade intelectual, a Palette Plotting, e não a Apple, será a única responsável por investigação, defesa, acordo e resolução dessa reivindicação.</p>
        <p className="text-muted-foreground mb-4">Você declara e garante que não está localizado em país sujeito a embargo do Governo dos EUA ou designado como país que “apoia o terrorismo”, e que não consta de lista do Governo dos EUA de partes proibidas ou restritas.</p>
        <p className="text-muted-foreground mb-4">O Aplicativo Licenciado é licenciado pela Palette Plotting LLC. Dúvidas, reclamações ou reivindicações relacionadas ao Aplicativo Licenciado devem ser enviadas para support@paletteplot.com. Para endereço postal, entre em contato pelo e-mail acima.</p>
        <p className="text-muted-foreground mb-4">Você deve cumprir termos aplicáveis de terceiros ao usar o Aplicativo Licenciado, por exemplo, não violar seu contrato de serviço de dados sem fio.</p>
        <p className="text-muted-foreground mb-4">Você e a Palette Plotting reconhecem e concordam que a Apple e suas subsidiárias são terceiras beneficiárias deste EULA e que, após sua aceitação, a Apple terá o direito de fazer cumprir este EULA contra você como terceira beneficiária.</p>
        <p className="text-muted-foreground mb-4">Você não pode copiar, modificar ou criar obras derivadas do Serviço; fazer engenharia reversa, descompilar ou desmontar o Serviço; remover avisos ou etiquetas proprietárias; alugar, arrendar, emprestar ou vender acesso ao Serviço; usar o Serviço para fins ilegais; ou interferir no Serviço ou nos servidores.</p>
        <p className="text-muted-foreground mb-4">O Serviço, incluindo todo conteúdo, recursos e funcionalidade, pertence à Palette Plotting e é protegido por leis de direitos autorais, marcas registradas e outras leis de propriedade intelectual. Este EULA não concede a você direitos de usar nossas marcas, logotipos ou outros elementos de marca.</p>
        <p className="text-muted-foreground mb-4">Você permite que a Palette Plotting hospede, armazene, transmita e processe tecnicamente seu conteúdo apenas conforme necessário para fornecer o Aplicativo Licenciado à sua conta, conforme descrito na seção Conteúdo do usuário acima.</p>
        <p className="text-muted-foreground mb-4">Esta licença permanece válida até ser encerrada. Podemos encerrar ou suspender seu acesso imediatamente, sem aviso prévio, por qualquer violação deste EULA. Após o encerramento, seu direito de usar o Serviço cessará imediatamente.</p>
        <p className="text-muted-foreground mb-4">O SERVIÇO É FORNECIDO “NO ESTADO EM QUE SE ENCONTRA” E “CONFORME DISPONÍVEL”, SEM GARANTIAS DE QUALQUER TIPO, EXPRESSAS OU IMPLÍCITAS, INCLUINDO GARANTIAS IMPLÍCITAS DE COMERCIALIZAÇÃO, ADEQUAÇÃO A DETERMINADO FIM OU NÃO VIOLAÇÃO.</p>
        <p className="text-muted-foreground mb-4">NA MÁXIMA MEDIDA PERMITIDA POR LEI, A PALETTE PLOTTING NÃO SERÁ RESPONSÁVEL POR DANOS INDIRETOS, INCIDENTAIS, ESPECIAIS, CONSEQUENCIAIS OU PUNITIVOS, NEM POR PERDA DE LUCROS OU RECEITAS, DIRETA OU INDIRETAMENTE INCORRIDOS.</p>
        <p className="text-muted-foreground mb-4">Reservamo-nos o direito de modificar, atualizar ou descontinuar o Serviço a qualquer momento. Também podemos atualizar este EULA periodicamente. Seu uso contínuo do Serviço após tais mudanças constitui aceitação do EULA atualizado.</p>
        <p className="text-muted-foreground mb-4">Este EULA será regido e interpretado de acordo com as leis aplicáveis, sem considerar disposições de conflito de leis. Para dúvidas sobre este EULA, contate-nos em support@paletteplot.com</p>
      </div>
    </>
  );
}
