export function TermsOfServiceContentIT() {
  return (
    <>
      <h1 className="text-4xl font-bold mb-6">Termini di utilizzo ed EULA</h1>
      <p className="text-sm text-muted-foreground mb-8">
        <strong>Data di efficacia:</strong> 13 gennaio 2025<br />
        <strong>Società:</strong> Palette Plotting LLC (&quot;Palette Plotting&quot;, &quot;noi&quot;, &quot;nostro&quot;, &quot;ci&quot;)
      </p>
      <p className="text-sm text-muted-foreground mb-8">
        <strong>Ultimo aggiornamento:</strong> 13 gennaio 2025
      </p>
      <div className="space-y-6 prose prose-sm max-w-none">
        <p className="text-muted-foreground mb-4"># Termini di utilizzo ed EULA</p>
        <h2 className="text-2xl font-semibold mb-4">Termini di utilizzo</h2>
        <p className="text-muted-foreground mb-4">I presenti Termini di utilizzo (&quot;Termini&quot;) regolano l’accesso e l’uso di Palette Plotting, inclusi tutti gli strumenti digitali, le funzionalità, i contenuti e i servizi offerti tramite il nostro sito web, app o PWA (collettivamente, il &quot;Servizio&quot;). Utilizzando il Servizio, accetti questi Termini. Se non accetti, non utilizzare il Servizio.</p>
        <h2 className="text-2xl font-semibold mb-4">1. Idoneità</h2>
        <p className="text-muted-foreground mb-4">Il Servizio è destinato a persone di almeno 18 anni. Non puoi utilizzare il Servizio se hai meno di 18 anni.</p>
        <h2 className="text-2xl font-semibold mb-4">2. Panoramica del Servizio</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting fornisce strumenti digitali destinati a supportare riflessione personale, definizione degli obiettivi, journaling, creazione audio e sviluppo della mentalità. Alcune parti del Servizio possono includere funzionalità automatizzate, suggerimenti generati dal sistema o contenuti assistiti dalla tecnologia. Il Servizio non costituisce consulenza medica, psicologica, terapeutica, finanziaria o legale e non sostituisce il supporto professionale. Possiamo aggiornare o modificare le funzionalità del Servizio in qualsiasi momento.</p>
        <h2 className="text-2xl font-semibold mb-4">3. Registrazione dell’account</h2>
        <p className="text-muted-foreground mb-4">Per utilizzare alcune funzionalità potresti dover creare un account. Accetti di fornire informazioni accurate, mantenere riservate le credenziali di accesso e informarci di qualsiasi uso non autorizzato. Sei responsabile delle attività che si verificano sotto il tuo account.</p>
        <h2 className="text-2xl font-semibold mb-4">4. Uso accettabile</h2>
        <p className="text-muted-foreground mb-4">Devi rispettare la nostra Politica di uso accettabile, incorporata per riferimento e disponibile separatamente. I comportamenti vietati includono, a titolo esemplificativo: molestie, abusi o condotte d’odio; caricamento o condivisione di contenuti illeciti o inappropriati; frode, impersonificazione o falsa dichiarazione; tentativi di interferire con il Servizio o interromperlo; uso del Servizio per scopi illegali o non sicuri; tentativi di aggirare le protezioni del sistema; sfruttamento di minori o pubblicazione di contenuti che coinvolgono minori in contesti inappropriati; caricamento di contenuti protetti da copyright senza autorizzazione. Possiamo sospendere o chiudere il tuo account per violazioni.</p>
        <h2 className="text-2xl font-semibold mb-4">5. Contenuti dell’utente</h2>
        <p className="text-muted-foreground mb-4">I &quot;Contenuti dell’utente&quot; includono testo, audio, note, voci di diario, affermazioni, composizioni musicali o altro materiale che inserisci o generi tramite il Servizio. Autorizzi Palette Plotting e i fornitori di infrastruttura che supportano il Servizio a ospitare, archiviare, trasmettere e trattare tecnicamente i tuoi Contenuti dell’utente solo nella misura necessaria per salvarli nel tuo account, restituirteli, sincronizzarli sui tuoi dispositivi ed eseguire le funzionalità che scegli di utilizzare, come generazione audio o formattazione. Questa autorizzazione è limitata, non esclusiva e gratuita e si applica solo finché il contenuto è archiviato per il tuo account. Non utilizziamo i tuoi Contenuti dell’utente privati per pubblicità, visualizzazione pubblica o sviluppo generale del prodotto a meno che tu non scelga separatamente di partecipare, ad esempio tramite l’addestramento dati facoltativo nelle Impostazioni. Palette Plotting non esamina regolarmente diari, affermazioni o audio privati per scopi editoriali o commerciali. Possiamo rimuovere contenuti che violano questi Termini o la Politica di uso accettabile.</p>
        <h2 className="text-2xl font-semibold mb-4">5a. Composizione musicale e copyright</h2>
        <p className="text-muted-foreground mb-4">Quando utilizzi la funzione Music Composer, riconosci e accetti che creerai solo composizioni musicali originali; non ricreerai, copierai né imiterai melodie, canzoni o opere musicali protette da copyright; sarai l’unico responsabile di garantire che le tue composizioni non violino copyright, marchi o diritti di proprietà intellettuale esistenti; e indennizzerai e manterrai indenne Palette Plotting da qualsiasi reclamo derivante da violazioni di copyright nelle tue composizioni. La violazione di questi termini può comportare la rimozione immediata dei contenuti e la chiusura dell’account.</p>
        <h2 className="text-2xl font-semibold mb-4">6. Contenuti assistiti dalla tecnologia e generati dal sistema</h2>
        <p className="text-muted-foreground mb-4">Alcune funzionalità possono offrire risposte automatizzate, suggerimenti o contenuti generati dall’IA per supportare la tua riflessione o i tuoi obiettivi creativi. Riconosci che tali contenuti possono essere imperfetti o incompleti, non sostituiscono la consulenza professionale e sei responsabile del modo in cui li utilizzi. Possiamo modificare o limitare queste funzionalità in qualsiasi momento.</p>
        <h2 className="text-2xl font-semibold mb-4">7. Notifiche degli obiettivi</h2>
        <p className="text-muted-foreground mb-4">Le notifiche degli obiettivi possono essere impostate tramite strumenti o servizi esterni scelti dall’utente, come integrazioni calendario, automazioni del dispositivo o scorciatoie a livello di sistema operativo. Questi strumenti possono ricordare agli utenti di rivedere obiettivi, aprire check-in settimanali o accedere a specifiche aree del Servizio in orari selezionati. Palette Plotting attualmente non invia notifiche degli obiettivi via SMS/e-mail e non controlla, gestisce né garantisce le prestazioni di calendari di terze parti, automazioni del dispositivo o funzionalità del sistema operativo. Palette Plotting non è responsabile per avvisi mancati, errori di consegna, errori di pianificazione, impostazioni del dispositivo o modifiche apportate da fornitori terzi. L’uso di strumenti di notifica esterni è facoltativo e interamente gestito dall’utente.</p>
        <h2 className="text-2xl font-semibold mb-4">8. Abbonamenti e fatturazione</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting offre piani di abbonamento, incluse opzioni mensili o annuali. I nomi e i prezzi dei piani possono cambiare. Le funzionalità incluse in ciascun livello, i livelli di accesso a funzionalità specifiche, i limiti come messaggi giornalieri, creazioni settimanali e quote di archiviazione, e altri benefici possono cambiare in qualsiasi momento senza preavviso. Ci riserviamo il diritto di modificare, aggiungere o rimuovere funzionalità, regolare i limiti, modificare i livelli di accesso o alterare qualsiasi aspetto dei livelli di abbonamento per mantenere la qualità del servizio, prevenire abusi o adattarci a esigenze operative. L’uso continuato del Servizio dopo tali modifiche costituisce accettazione. Tutte le vendite sono definitive salvo quanto richiesto dalla legge applicabile. Gli abbonamenti in-app acquistati tramite Android utilizzano il sistema di fatturazione Google Play. Pagamenti, rinnovi, cancellazioni e richieste di rimborso sono gestiti secondo le politiche di Google; le richieste devono essere inviate tramite Google Play, non a Palette Plotting. Abbonandoti, autorizzi la fatturazione ricorrente fino alla cancellazione. Le cancellazioni hanno effetto alla fine del periodo di fatturazione corrente. Non offriamo rimborsi per periodi parziali o tempo inutilizzato. In caso di scadenza o cancellazione, i tuoi contenuti utente, inclusi analisi delle strutture di credenze, voci di diario, set di affermazioni, audio creati nel Servizio e altri media o dati creati tramite il Servizio, possono essere eliminati permanentemente. Non garantiamo la conservazione dei dati.</p>
        <h2 className="text-2xl font-semibold mb-4">9. Proprietà intellettuale</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting e tutti i contenuti, branding, design e materiali associati sono di proprietà di Palette Plotting LLC o dei suoi licenzianti. Non puoi copiare o distribuire il Servizio, effettuare reverse engineering del software, usare impropriamente marchi o branding, o creare opere derivate dalla piattaforma.</p>
        <h2 className="text-2xl font-semibold mb-4">10. Modifiche del Servizio</h2>
        <p className="text-muted-foreground mb-4">Possiamo modificare, interrompere o aggiornare qualsiasi parte del Servizio in qualsiasi momento. Non siamo responsabili per modifiche, sospensioni o interruzioni del servizio.</p>
        <h2 className="text-2xl font-semibold mb-4">11. Esclusioni di garanzia</h2>
        <p className="text-muted-foreground mb-4">Il Servizio è fornito &quot;così com’è&quot; e &quot;come disponibile&quot;. Non garantiamo risultati specifici, disponibilità ininterrotta o accuratezza dei contenuti generati dal sistema. Escludiamo tutte le garanzie nella massima misura consentita dalla legge.</p>
        <h2 className="text-2xl font-semibold mb-4">12. Limitazione di responsabilità</h2>
        <p className="text-muted-foreground mb-4">Nella massima misura consentita dalla legge, Palette Plotting LLC non è responsabile per danni indiretti, incidentali, speciali, consequenziali o punitivi derivanti dall’uso del Servizio. La nostra responsabilità totale per qualsiasi reclamo non supererà l’importo pagato in quote di abbonamento nei 12 mesi precedenti il reclamo.</p>
        <h2 className="text-2xl font-semibold mb-4">13. Indennizzo</h2>
        <p className="text-muted-foreground mb-4">Accetti di indennizzare e tenere indenne Palette Plotting LLC da reclami derivanti dal tuo uso improprio del Servizio, dalla tua violazione di questi Termini o dai tuoi Contenuti dell’utente.</p>
        <h2 className="text-2xl font-semibold mb-4">14. Legge applicabile</h2>
        <p className="text-muted-foreground mb-4">Questi Termini sono regolati dalle leggi dello Stato dell’Illinois, senza riguardo alle norme sui conflitti di legge.</p>
        <h2 className="text-2xl font-semibold mb-4">15. Modifiche ai Termini</h2>
        <p className="text-muted-foreground mb-4">Possiamo aggiornare questi Termini. L’uso continuato del Servizio indica accettazione della versione aggiornata.</p>
        <h2 className="text-2xl font-semibold mb-4">16. Contatto</h2>
        <p className="text-muted-foreground mb-4">Le domande possono essere inviate a: support@paletteplot.com</p>
        <h2 className="text-2xl font-semibold mb-4">EULA</h2>
        <p className="text-muted-foreground mb-4">La presente End User License Agreement (&quot;EULA&quot;) è un accordo legale esclusivamente tra te e Palette Plotting LLC, e non con Apple, Inc. (&quot;Apple&quot;). Palette Plotting è l’unica responsabile dell’Applicazione concessa in licenza e del relativo contenuto. Questa EULA non può prevedere regole d’uso in conflitto con gli Apple Media Services Terms and Conditions alla Data di efficacia, che riconosci di aver avuto l’opportunità di esaminare. Accedendo a Palette Plotting o utilizzandola, accetti di essere vincolato da questa EULA.</p>
        <p className="text-muted-foreground mb-4">Subordinatamente al rispetto di questa EULA, Palette Plotting ti concede una licenza limitata, non esclusiva, non trasferibile e revocabile per utilizzare l’Applicazione concessa in licenza su prodotti a marchio Apple che possiedi o controlli, come consentito dalle Usage Rules degli Apple Media Services Terms and Conditions. La licenza consente l’accesso e l’uso dell’Applicazione da parte di altri account associati a te tramite Family Sharing o acquisto a volume.</p>
        <p className="text-muted-foreground mb-4">Palette Plotting è l’unica responsabile della manutenzione e del supporto relativi all’Applicazione, come specificato in questa EULA o richiesto dalla legge. Riconosci che Apple non ha alcun obbligo di fornire manutenzione o supporto.</p>
        <p className="text-muted-foreground mb-4">Palette Plotting è l’unica responsabile di eventuali garanzie del prodotto, espresse o implicite per legge, nella misura in cui non siano efficacemente escluse. Per gli acquisti tramite App Store, inclusi abbonamenti in-app, in caso di mancata conformità dell’Applicazione a una garanzia applicabile, puoi informare Apple e Apple rimborserà il prezzo di acquisto per tale acquisto App Store. Ciò non si applica agli acquisti tramite sito web o altri metodi, come Stripe, disciplinati dai nostri Termini generali e dalla nostra politica di fatturazione. Nella massima misura consentita, Apple non avrà altri obblighi di garanzia, e ogni altra pretesa, perdita, responsabilità, danno, costo o spesa attribuibile a mancata conformità sarà di esclusiva responsabilità di Palette Plotting.</p>
        <p className="text-muted-foreground mb-4">Tu e Palette Plotting riconoscete che Palette Plotting, non Apple, è responsabile di gestire qualsiasi reclamo tuo o di terzi relativo all’Applicazione o al tuo possesso e/o uso dell’Applicazione, inclusi reclami di responsabilità da prodotto, mancata conformità a requisiti legali o regolamentari, e reclami derivanti da legislazione su consumatori, privacy o simili. Questa EULA non può limitare la responsabilità di Palette Plotting oltre quanto consentito dalla legge.</p>
        <p className="text-muted-foreground mb-4">In caso di reclamo di terzi secondo cui l’Applicazione o il tuo possesso e uso dell’Applicazione viola diritti di proprietà intellettuale, Palette Plotting, non Apple, sarà l’unica responsabile di indagine, difesa, transazione e definizione di tale reclamo.</p>
        <p className="text-muted-foreground mb-4">Dichiari e garantisci di non trovarti in un paese soggetto a embargo del governo degli Stati Uniti o designato come paese &quot;sostenitore del terrorismo&quot;, e di non essere incluso in alcuna lista del governo degli Stati Uniti di soggetti vietati o limitati.</p>
        <p className="text-muted-foreground mb-4">L’Applicazione è concessa in licenza da Palette Plotting LLC. Domande, reclami o richieste relative all’Applicazione devono essere inviati a support@paletteplot.com. Per un indirizzo postale, contattaci all’e-mail sopra indicata.</p>
        <p className="text-muted-foreground mb-4">Devi rispettare i termini applicabili di terze parti quando usi l’Applicazione, ad esempio non violare il tuo contratto di servizio dati wireless.</p>
        <p className="text-muted-foreground mb-4">Tu e Palette Plotting riconoscete che Apple e le sue controllate sono terzi beneficiari di questa EULA e che, alla tua accettazione, Apple avrà il diritto di far valere questa EULA contro di te come terzo beneficiario.</p>
        <p className="text-muted-foreground mb-4">Non puoi copiare, modificare o creare opere derivate dal Servizio; effettuare reverse engineering, decompilare o disassemblare il Servizio; rimuovere avvisi o etichette proprietarie; affittare, concedere in leasing, prestare o vendere l’accesso al Servizio; utilizzare il Servizio per scopi illegali; o interferire con il Servizio o i server.</p>
        <p className="text-muted-foreground mb-4">Il Servizio, inclusi contenuti, funzionalità e funzioni, appartiene a Palette Plotting ed è protetto dalle leggi su copyright, marchi e proprietà intellettuale. Questa EULA non ti concede diritti di usare i nostri marchi, loghi o altri elementi del brand.</p>
        <p className="text-muted-foreground mb-4">Autorizzi Palette Plotting a ospitare, archiviare, trasmettere e trattare tecnicamente i tuoi contenuti solo nella misura necessaria a fornire l’Applicazione al tuo account, come descritto nella sezione Contenuti dell’utente.</p>
        <p className="text-muted-foreground mb-4">Questa licenza resta efficace fino alla cessazione. Possiamo terminare o sospendere il tuo accesso immediatamente, senza preavviso, per qualsiasi violazione della EULA. Alla cessazione, il tuo diritto di usare il Servizio cessa immediatamente.</p>
        <p className="text-muted-foreground mb-4">IL SERVIZIO È FORNITO &quot;COSÌ COM’È&quot; E &quot;COME DISPONIBILE&quot; SENZA GARANZIE DI ALCUN TIPO, ESPRESSE O IMPLICITE, INCLUSE LE GARANZIE IMPLICITE DI COMMERCIABILITÀ, IDONEITÀ A UNO SCOPO PARTICOLARE O NON VIOLAZIONE.</p>
        <p className="text-muted-foreground mb-4">NELLA MASSIMA MISURA CONSENTITA DALLA LEGGE, PALETTE PLOTTING NON SARÀ RESPONSABILE PER DANNI INDIRETTI, INCIDENTALI, SPECIALI, CONSEQUENZIALI O PUNITIVI, O PER PERDITE DI PROFITTI O RICAVI, DIRETTE O INDIRETTE.</p>
        <p className="text-muted-foreground mb-4">Ci riserviamo il diritto di modificare, aggiornare o interrompere il Servizio in qualsiasi momento. Possiamo anche aggiornare questa EULA di volta in volta. L’uso continuato del Servizio dopo tali modifiche costituisce accettazione della EULA aggiornata.</p>
        <p className="text-muted-foreground mb-4">Questa EULA sarà disciplinata e interpretata in conformità alle leggi applicabili, senza riguardo alle norme sui conflitti di legge. Per domande sulla EULA, contattaci a support@paletteplot.com</p>
      </div>
    </>
  );
}
