export function TermsOfServiceContentFR() {
  return (
    <>
      <h1 className="text-4xl font-bold mb-6">Conditions d’utilisation et EULA</h1>
      <p className="text-sm text-muted-foreground mb-8">
        <strong>Date d’entrée en vigueur :</strong> 13 janvier 2025<br />
        <strong>Société :</strong> Palette Plotting LLC (&quot;Palette Plotting&quot;, &quot;nous&quot;, &quot;notre&quot;, &quot;nos&quot;)
      </p>
      <p className="text-sm text-muted-foreground mb-8">
        <strong>Dernière mise à jour :</strong> 13 janvier 2025
      </p>
      <div className="space-y-6 prose prose-sm max-w-none">
        <p className="text-muted-foreground mb-4"># Conditions d’utilisation et EULA</p>
        <h2 className="text-2xl font-semibold mb-4">Conditions d’utilisation</h2>
        <p className="text-muted-foreground mb-4">Les présentes Conditions d’utilisation (&quot;Conditions&quot;) régissent votre accès à Palette Plotting et votre utilisation de Palette Plotting, y compris tous les outils numériques, fonctionnalités, contenus et services proposés via notre site web, notre application ou notre PWA (collectivement, le &quot;Service&quot;). En utilisant le Service, vous acceptez ces Conditions. Si vous n’acceptez pas ces Conditions, n’utilisez pas le Service.</p>
        <h2 className="text-2xl font-semibold mb-4">1. Admissibilité</h2>
        <p className="text-muted-foreground mb-4">Le Service est destiné aux personnes âgées de 18 ans ou plus. Vous ne pouvez pas utiliser le Service si vous avez moins de 18 ans.</p>
        <h2 className="text-2xl font-semibold mb-4">2. Présentation du Service</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting fournit des outils numériques destinés à soutenir la réflexion personnelle, la définition d’objectifs, le journaling, la création audio et le développement de l’état d’esprit. Certaines parties du Service peuvent inclure des fonctionnalités automatisées, des suggestions générées par le système ou du contenu assisté par la technologie. Le Service ne constitue pas un conseil médical, psychologique, thérapeutique, financier ou juridique et ne remplace pas un accompagnement professionnel. Nous pouvons mettre à jour ou modifier les fonctionnalités du Service à tout moment.</p>
        <h2 className="text-2xl font-semibold mb-4">3. Inscription au compte</h2>
        <p className="text-muted-foreground mb-4">Pour utiliser certaines fonctionnalités, vous devrez peut-être créer un compte. Vous acceptez de fournir des informations exactes, de préserver la confidentialité de vos identifiants de connexion et de nous signaler toute utilisation non autorisée. Vous êtes responsable de toute activité effectuée depuis votre compte.</p>
        <h2 className="text-2xl font-semibold mb-4">4. Utilisation acceptable</h2>
        <p className="text-muted-foreground mb-4">Vous devez respecter notre Politique d’utilisation acceptable, intégrée par référence et disponible séparément. Les comportements interdits comprennent notamment le harcèlement, les abus ou les conduites haineuses ; le téléversement ou le partage de contenu illicite ou inapproprié ; la fraude, l’usurpation d’identité ou la fausse déclaration ; toute tentative d’interférer avec le Service ou de le perturber ; l’utilisation du Service à des fins illégales ou dangereuses ; toute tentative de contourner les protections du système ; l’exploitation de mineurs ou la publication de contenu impliquant des mineurs dans un contexte inapproprié ; et le téléversement de contenu protégé par le droit d’auteur sans autorisation. Nous pouvons suspendre ou résilier votre compte en cas de violation.</p>
        <h2 className="text-2xl font-semibold mb-4">5. Contenu utilisateur</h2>
        <p className="text-muted-foreground mb-4">Le &quot;Contenu utilisateur&quot; comprend les textes, fichiers audio, notes, entrées de journal, affirmations, compositions musicales ou autres éléments que vous saisissez ou générez via le Service. Vous autorisez Palette Plotting et les fournisseurs d’infrastructure qui soutiennent le Service à héberger, stocker, transmettre et traiter techniquement votre Contenu utilisateur uniquement dans la mesure nécessaire pour l’enregistrer dans votre compte, vous le restituer, le synchroniser sur vos appareils et exécuter les fonctionnalités que vous choisissez d’utiliser, telles que la génération audio ou la mise en forme. Cette autorisation est limitée, non exclusive et libre de redevances, et ne s’applique que tant que le contenu est stocké pour votre compte. Nous n’utilisons pas votre Contenu utilisateur privé à des fins publicitaires, d’affichage public ou de développement général du produit, sauf si vous y consentez séparément, par exemple via l’entraînement de données facultatif dans les Paramètres. Palette Plotting n’examine pas régulièrement les journaux, affirmations ou fichiers audio privés à des fins éditoriales ou commerciales. Nous pouvons supprimer tout contenu qui viole ces Conditions ou la Politique d’utilisation acceptable.</p>
        <h2 className="text-2xl font-semibold mb-4">5a. Composition musicale et droit d’auteur</h2>
        <p className="text-muted-foreground mb-4">Lorsque vous utilisez la fonctionnalité Music Composer, vous reconnaissez et acceptez que vous créerez uniquement des compositions musicales originales ; que vous ne recréerez, ne copierez ni n’imiterez des mélodies, chansons ou œuvres musicales protégées par le droit d’auteur ; que vous êtes seul responsable de vous assurer que vos compositions ne portent pas atteinte à des droits d’auteur, marques ou autres droits de propriété intellectuelle existants ; et que vous indemniserez et dégagerez Palette Plotting de toute responsabilité pour toute réclamation découlant d’une violation du droit d’auteur dans vos compositions. Toute violation de ces conditions peut entraîner la suppression immédiate du contenu et la résiliation du compte.</p>
        <h2 className="text-2xl font-semibold mb-4">6. Contenu assisté par la technologie et généré par le système</h2>
        <p className="text-muted-foreground mb-4">Certaines fonctionnalités peuvent offrir des réponses automatisées, des suggestions ou du contenu généré par l’IA pour soutenir votre réflexion ou vos objectifs créatifs. Vous reconnaissez que ce contenu peut être imparfait ou incomplet, qu’il ne remplace pas un conseil professionnel et que vous êtes responsable de l’usage que vous en faites. Nous pouvons ajuster ou limiter ces fonctionnalités à tout moment.</p>
        <h2 className="text-2xl font-semibold mb-4">7. Notifications d’objectifs</h2>
        <p className="text-muted-foreground mb-4">Les notifications d’objectifs peuvent être configurées au moyen d’outils ou de services externes choisis par l’utilisateur, tels que des intégrations de calendrier, des automatisations d’appareil ou des raccourcis au niveau du système d’exploitation. Ces outils peuvent servir à rappeler aux utilisateurs de revoir leurs objectifs, d’ouvrir des bilans hebdomadaires ou d’accéder à certaines zones du Service à des moments choisis. Palette Plotting n’envoie actuellement pas de notifications d’objectifs par SMS/e-mail et ne contrôle, n’exploite ni ne garantit les performances des calendriers tiers, automatisations d’appareil ou fonctionnalités du système d’exploitation. Palette Plotting n’est pas responsable des alertes manquées, échecs de livraison, erreurs de planification, paramètres de l’appareil ou changements effectués par des fournisseurs tiers. L’utilisation d’outils de notification externes est facultative et entièrement gérée par l’utilisateur.</p>
        <h2 className="text-2xl font-semibold mb-4">8. Abonnements et facturation</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting propose des formules d’abonnement, notamment des options mensuelles ou annuelles. Les noms et prix des formules peuvent changer. Les fonctionnalités incluses dans chaque niveau d’abonnement, les niveaux d’accès à certaines fonctionnalités, les limites de taux, telles que les limites de messages quotidiens, les limites de création hebdomadaires et les quotas de stockage, ainsi que les autres avantages d’abonnement peuvent changer à tout moment sans préavis. Nous nous réservons le droit de modifier, ajouter ou supprimer des fonctionnalités, d’ajuster les limites, de modifier les niveaux d’accès ou de changer tout aspect des niveaux d’abonnement selon les besoins afin de maintenir la qualité du service, prévenir les abus ou répondre aux exigences opérationnelles. L’utilisation continue du Service après ces changements constitue votre acceptation des modifications. Toutes les ventes sont définitives, sauf lorsque la loi applicable l’exige. Les abonnements intégrés achetés via l’application Android utilisent le système de facturation de Google Play. Les paiements, renouvellements, annulations et demandes de remboursement sont traités conformément aux politiques de Google ; les demandes de remboursement doivent être soumises via Google Play, et non à Palette Plotting. En vous abonnant, vous autorisez la facturation récurrente jusqu’à annulation. Les annulations prennent effet à la fin de la période de facturation en cours. Nous n’offrons pas de remboursement pour les périodes partielles ou le temps non utilisé. En cas d’expiration ou d’annulation d’un abonnement, votre contenu utilisateur, y compris notamment les analyses de structure de croyances, entrées de journal, ensembles d’affirmations, fichiers audio créés dans le Service et autres médias ou données créés via le Service, peut être supprimé définitivement. Même si nous pouvons conserver certaines données pendant une période limitée après l’annulation, nous ne garantissons pas la conservation des données, et du contenu peut être perdu en raison d’erreurs système, de problèmes techniques ou de changements de politique.</p>
        <h2 className="text-2xl font-semibold mb-4">9. Propriété intellectuelle</h2>
        <p className="text-muted-foreground mb-4">Palette Plotting et tous les contenus, marques, designs et éléments associés appartiennent à Palette Plotting LLC ou à ses concédants. Vous ne pouvez pas copier ou distribuer le Service, effectuer de l’ingénierie inverse sur le logiciel, utiliser abusivement les marques ou l’identité de marque, ni créer des œuvres dérivées de la plateforme.</p>
        <h2 className="text-2xl font-semibold mb-4">10. Modifications du Service</h2>
        <p className="text-muted-foreground mb-4">Nous pouvons modifier, interrompre ou mettre à jour toute partie du Service à tout moment. Nous ne sommes pas responsables des changements, suspensions ou interruptions de service.</p>
        <h2 className="text-2xl font-semibold mb-4">11. Avis de non-responsabilité</h2>
        <p className="text-muted-foreground mb-4">Le Service est fourni &quot;tel quel&quot; et &quot;selon disponibilité&quot;. Nous ne garantissons pas des résultats particuliers, une disponibilité ininterrompue ni l’exactitude du contenu généré par le système. Nous excluons toutes les garanties dans toute la mesure permise par la loi.</p>
        <h2 className="text-2xl font-semibold mb-4">12. Limitation de responsabilité</h2>
        <p className="text-muted-foreground mb-4">Dans toute la mesure permise par la loi, Palette Plotting LLC ne pourra être tenue responsable de dommages indirects, accessoires, spéciaux, consécutifs ou punitifs découlant de votre utilisation du Service. Notre responsabilité totale pour toute réclamation ne dépassera pas le montant que vous avez payé en frais d’abonnement au cours des 12 mois précédant la réclamation.</p>
        <h2 className="text-2xl font-semibold mb-4">13. Indemnisation</h2>
        <p className="text-muted-foreground mb-4">Vous acceptez d’indemniser et de dégager Palette Plotting LLC de toute responsabilité pour les réclamations découlant de votre mauvaise utilisation du Service, de votre violation de ces Conditions ou de votre Contenu utilisateur.</p>
        <h2 className="text-2xl font-semibold mb-4">14. Loi applicable</h2>
        <p className="text-muted-foreground mb-4">Ces Conditions sont régies par les lois de l’État de l’Illinois, sans égard aux règles de conflit de lois.</p>
        <h2 className="text-2xl font-semibold mb-4">15. Modifications des Conditions</h2>
        <p className="text-muted-foreground mb-4">Nous pouvons mettre à jour ces Conditions. L’utilisation continue du Service vaut acceptation de la version mise à jour.</p>
        <h2 className="text-2xl font-semibold mb-4">16. Contact</h2>
        <p className="text-muted-foreground mb-4">Les questions peuvent être adressées à : support@paletteplot.com</p>
        <h2 className="text-2xl font-semibold mb-4">EULA</h2>
        <p className="text-muted-foreground mb-4">La présente End User License Agreement (&quot;EULA&quot;) est un accord juridique conclu uniquement entre vous et Palette Plotting LLC, et non avec Apple, Inc. (&quot;Apple&quot;). Palette Plotting est seule responsable de l’Application sous licence et de son contenu. Cette EULA ne peut pas prévoir de règles d’utilisation contraires aux Apple Media Services Terms and Conditions à la Date d’entrée en vigueur, que vous reconnaissez avoir eu l’occasion de consulter. En accédant à Palette Plotting ou en l’utilisant, vous acceptez d’être lié par cette EULA.</p>
        <p className="text-muted-foreground mb-4">Sous réserve de votre respect de cette EULA, Palette Plotting vous accorde une licence limitée, non exclusive, non transférable et révocable pour utiliser l’Application sous licence sur tout produit de marque Apple que vous possédez ou contrôlez, conformément aux Règles d’utilisation prévues par les Apple Media Services Terms and Conditions. Cette licence permet l’accès à l’Application sous licence et son utilisation par d’autres comptes qui vous sont associés via Family Sharing ou l’achat en volume.</p>
        <p className="text-muted-foreground mb-4">Palette Plotting est seule responsable de toute maintenance et assistance relative à l’Application sous licence, comme précisé dans cette EULA ou exigé par la loi applicable. Vous reconnaissez qu’Apple n’a aucune obligation de fournir des services de maintenance ou d’assistance concernant l’Application sous licence.</p>
        <p className="text-muted-foreground mb-4">Palette Plotting est seule responsable de toute garantie produit, expresse ou implicite par la loi, dans la mesure où elle n’est pas valablement exclue. Pour les achats effectués via l’App Store, y compris les abonnements intégrés, en cas de défaut de conformité de l’Application sous licence à une garantie applicable, vous pouvez en informer Apple, et Apple vous remboursera le prix d’achat correspondant à cet achat App Store. Cela ne s’applique pas aux abonnements ou achats effectués via notre site web ou d’autres méthodes de paiement, par exemple Stripe, qui sont régis par nos Conditions d’utilisation générales et notre politique de facturation. Dans la mesure maximale permise par la loi, Apple n’aura aucune autre obligation de garantie concernant l’Application sous licence, et toute autre réclamation, perte, responsabilité, dommage, coût ou dépense attribuable à un défaut de conformité à une garantie relèvera de la seule responsabilité de Palette Plotting.</p>
        <p className="text-muted-foreground mb-4">Vous et Palette Plotting reconnaissez que Palette Plotting, et non Apple, est responsable de traiter toute réclamation de votre part ou de la part d’un tiers relative à l’Application sous licence ou à votre possession et/ou utilisation de celle-ci, y compris les réclamations en responsabilité du fait des produits, les réclamations selon lesquelles l’Application sous licence ne respecte pas une exigence légale ou réglementaire applicable, et les réclamations fondées sur la protection des consommateurs, la vie privée ou une législation similaire. Cette EULA ne peut pas limiter la responsabilité de Palette Plotting envers vous au-delà de ce qui est permis par la loi applicable.</p>
        <p className="text-muted-foreground mb-4">En cas de réclamation d’un tiers selon laquelle l’Application sous licence ou votre possession et utilisation de celle-ci porte atteinte aux droits de propriété intellectuelle de ce tiers, Palette Plotting, et non Apple, sera seule responsable de l’enquête, de la défense, du règlement et de la résolution de cette réclamation.</p>
        <p className="text-muted-foreground mb-4">Vous déclarez et garantissez que vous ne vous trouvez pas dans un pays soumis à un embargo du gouvernement des États-Unis ou désigné par le gouvernement des États-Unis comme un pays &quot;soutenant le terrorisme&quot;, et que vous ne figurez sur aucune liste du gouvernement des États-Unis de parties interdites ou restreintes.</p>
        <p className="text-muted-foreground mb-4">L’Application sous licence est concédée sous licence par Palette Plotting LLC. Les questions, plaintes ou réclamations concernant l’Application sous licence doivent être adressées à support@paletteplot.com. Pour obtenir une adresse postale, contactez-nous à l’adresse e-mail ci-dessus.</p>
        <p className="text-muted-foreground mb-4">Vous devez respecter les conditions applicables des tiers lorsque vous utilisez l’Application sous licence, par exemple ne pas violer votre contrat de service de données sans fil.</p>
        <p className="text-muted-foreground mb-4">Vous et Palette Plotting reconnaissez qu’Apple et ses filiales sont des tiers bénéficiaires de cette EULA et qu’après votre acceptation de ses conditions, Apple aura le droit, et sera réputée avoir accepté le droit, de faire appliquer cette EULA contre vous en tant que tiers bénéficiaire.</p>
        <p className="text-muted-foreground mb-4">Vous ne pouvez pas copier, modifier ou créer des œuvres dérivées du Service ; effectuer de l’ingénierie inverse, décompiler ou désassembler le Service ; supprimer des avis ou étiquettes de propriété ; louer, prêter ou vendre l’accès au Service ; utiliser le Service à des fins illégales ; ou interférer avec le Service ou les serveurs.</p>
        <p className="text-muted-foreground mb-4">Le Service, y compris tout le contenu, les fonctionnalités et la fonctionnalité, appartient à Palette Plotting et est protégé par les lois sur le droit d’auteur, les marques et autres lois sur la propriété intellectuelle. Cette EULA ne vous accorde aucun droit d’utiliser nos marques, logos ou autres éléments de marque.</p>
        <p className="text-muted-foreground mb-4">Vous autorisez Palette Plotting à héberger, stocker, transmettre et traiter techniquement votre contenu uniquement dans la mesure nécessaire pour fournir l’Application sous licence à votre compte, comme décrit dans la section Contenu utilisateur ci-dessus.</p>
        <p className="text-muted-foreground mb-4">Cette licence reste en vigueur jusqu’à sa résiliation. Nous pouvons résilier ou suspendre votre accès immédiatement, sans préavis, en cas de violation de cette EULA. À la résiliation, votre droit d’utiliser le Service cesse immédiatement.</p>
        <p className="text-muted-foreground mb-4">LE SERVICE EST FOURNI &quot;TEL QUEL&quot; ET &quot;SELON DISPONIBILITÉ&quot; SANS GARANTIE D’AUCUNE SORTE, EXPRESSE OU IMPLICITE, Y COMPRIS NOTAMMENT LES GARANTIES IMPLICITES DE QUALITÉ MARCHANDE, D’ADÉQUATION À UN USAGE PARTICULIER OU DE NON-CONTREFAÇON.</p>
        <p className="text-muted-foreground mb-4">DANS TOUTE LA MESURE PERMISE PAR LA LOI, PALETTE PLOTTING NE SERA PAS RESPONSABLE DES DOMMAGES INDIRECTS, ACCESSOIRES, SPÉCIAUX, CONSÉCUTIFS OU PUNITIFS, NI DE TOUTE PERTE DE PROFITS OU DE REVENUS, QU’ELLE SOIT DIRECTE OU INDIRECTE.</p>
        <p className="text-muted-foreground mb-4">Nous nous réservons le droit de modifier, mettre à jour ou interrompre le Service à tout moment. Nous pouvons également mettre à jour cette EULA de temps à autre. Votre utilisation continue du Service après ces changements constitue votre acceptation de l’EULA mise à jour.</p>
        <p className="text-muted-foreground mb-4">Cette EULA est régie et interprétée conformément aux lois applicables, sans égard aux règles de conflit de lois.</p>
        <p className="text-muted-foreground mb-4">Pour toute question concernant cette EULA, contactez-nous à support@paletteplot.com</p>
      </div>
    </>
  );
}
